import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' }
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {
          script {			
           sh "echo 'hola mundo'"
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           sh "echo 'se ejeccuta always'"
      }
      success {
            sh "echo 'se ejecuta solo si la tarea termina bien success'"
        }

      failure {
            sh "echo 'se ejecuta solo si la tarea falla failure'"
      }
      
  }
}  

